### PR TITLE
fix upload validation to work with SS 3.2+

### PR DESCRIPTION
**Pull request by xini**
basically overwrites file size check completely (isValidSize always returns true).

### CODE REVIEW

**Comment by micschk** [comment]
Thanks for this!

**Comment by xini** [comment]
no worries. can you please tag a release with this? thanks!

**Comment by micschk** [comment]
@xini, I noticed this commit in FW 3.5.1 - since you're probably more into the code of this module than I am currently; do you think this has implications for ChunkedUploadfield?
https://github.com/silverstripe/silverstripe-framework/commit/dd9ade429454b1053ab5c2003663eeb66b5866d6

**Comment by xini** [comment]
Hi @micschk,
This doesnt impact the ChunkedUploadField. It is correct to remove the code in UploadField because the limits are handled in Upload_Validator already. 
Bu I noticed that the ChunkedUploadField doesn't work in IE11 when uploading files larger than the PHP limits. For some reason the overwrite doesn't work there. The field shows `TypeError: Unable to get property '0' of undefined or null reference` as an error message, the underlying error is `<b>Warning</b>:  POST Content-Length of 38646695 bytes exceeds the limit of 26214400 bytes in <b>Unknown</b> on line <b>0</b>`.
Any ideas?
Cheers, Flo

**Comment by micschk** [comment]
I'd expect one of the JS dependencies to be causing this issue (IE11
binary/blob issue?)
I cannot make it a priority to look into IE issues at the moment, but you
could try to update some of the JS libs to see if that resolves it.

Some links I found about comparable issues;
https://github.com/zulip/zulip/issues/245
http://salesforce.stackexchange.com/questions/33567/cant-upload-files-with-ie11-does-not-support-binary-blobs

>

**Comment by xini** [comment]
I see. I told my client to use Chrome for the uploads, so no urgency here. will follow up when I get some time... Thanks!

**Pull request merged**
