### PR TITLE
another fix to the validator to fool js validation

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by micschk** [comment]
@xini tag 1.1 includes this and your previous PR

**Comment by xini** [comment]
Hi @micschk could you please update packagist with this release? you can add the Packagist Service on https://github.com/micschk/silverstripe-chunkeduploadfield/settings/installations to do that automatically on each release. Thanks.

**Comment by micschk** [comment]
I've re-added packagist and the release seems to have propagated now.

**Comment by xini** [comment]
Thanks! ;)

**Pull request merged**
